---
# Description
#
# USAGE
#
# - uses: git-secrets/TBD
name: git-secrets
description: Run git secrets
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        repository: 'awslabs/git-secrets'
        ref: 'ad82d68ee924906a0401dfd48de5057731a9bc84' #v1.3.0
    - env:
        PREFIX : ${{ runner.temp }}/git-secrets-prefix
        MANPREFIX: ${{ runner.temp }}/git-secrets-manprefix
      name: Make
      run: |
        make install
      shell: bash
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        path: ${{ runner.temp }}/git-secrets-checkout
        depth: 0
    - name: Debug
      run: |
        echo $GITHUB_WORKSPACE
        ls -R $GITHUB_WORKSPACE
        ls -R ${{ runner.temp }}/git-secrets-checkout
        ls -l ${{ runner.temp }}/git-secrets-prefix/bin/
      shell: bash
    - name: Install
      run: |
        cd ${{ runner.temp }}/git-secrets-checkout
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --install
      shell: bash
    - name: Register
      run: |
        cd ${{ runner.temp }}/git-secrets-checkout
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --register-aws
      shell: bash
    - name: Scan
      run: |
        cd ${{ runner.temp }}/git-secrets-checkout
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --scan $GITHUB_WORKSPACE
      shell: bash
