---
# EXAMPLE USAGE
#
# - uses: git-secrets/scan
#   with:
#     checkout: true
#     version: '5357e18bc27b42a827b6780564ea873a72ca1f01'

branding:
  color: 'orange'
  icon: 'activity'
description: Scan the repository history with git-secrets with register-aws
inputs:
  checkout:
    default: true
    description: 'If "true" will checkout with fetch-depth equal to zero and all the rest defaults, if "false" assumed already checked out'
    required: false
    type: boolean
  fetch-depth:
    default: '0'
    description: 'If "true" will checkout with fetch-depth equal to zero and all the rest defaults, if "false" assumed already checked out'
    required: false
    type: string
  ref:
    default: '5357e18bc27b42a827b6780564ea873a72ca1f01'
    description: 'The version or hash of git-secrets'
    required: false
    type: string
  scan-type:
    default: '--scan-history'
    description: 'The type of scan'
    required: false
    type: choice
    options:
      - '--scan-history'
      - '--scan'
name: scan
runs:
  steps:

    - name: Checkout awslabs/git-secrets
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        repository: 'awslabs/git-secrets'
        ref: ${{ inputs.ref }}
        path: git-secrets-repository
    - run: |
        ls $GITHUB_WORKSPACE/git-secrets-repository;
      shell: bash
    - env:
        PREFIX : ${{ runner.temp }}/git-secrets-prefix
        MANPREFIX: ${{ runner.temp }}/git-secrets-manprefix
      name: Install git-secrets
      run: |
        # make git-secrets
        cd $GITHUB_WORKSPACE/git-secrets-repository; # MUST MATCH ABOVE
        make install;
        cd $GITHUB_WORKSPACE
        rm -r -f $GITHUB_WORKSPACE/git-secrets-repository # MUST MATCH ABOVE
      shell: bash

    - if: inputs.checkout
      name: Checkout the repository to scan history
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }} # to scan history

    - name: Install git-secrets into the repository
      run: |
        # install git-secrets
        export PATH=$PATH:${{ runner.temp }}/git-secrets-prefix/bin/

        echo "Install git-secrets"
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --install
        echo "Register AWS"
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --register-aws

        echo "Test AWS Secrets Detection"
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --aws-provider | ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --scan - || echo "Detected secrets correctly"

        echo "List git-secrets"
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --list
      shell: bash

    - name: Scan with git-secrets
      run: |      
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets ${{ inputs.scan-type }}
      shell: bash

  using: "composite"
