---
# Description
#
# USAGE
#
# - uses: git-secrets/TBD
name: git-secrets
description: Run git secrets
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        repository: 'awslabs/git-secrets'
        ref: '5357e18bc27b42a827b6780564ea873a72ca1f01' # 2025-06-30 because tags are outdated
    - env:
        PREFIX : ${{ runner.temp }}/git-secrets-prefix
        MANPREFIX: ${{ runner.temp }}/git-secrets-manprefix
      name: Make
      run: |
        # make git-secrets
        make install
      shell: bash
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        path: git-secrets-checkout
        fetch-depth: 0
    - name: Install
      run: |
        # install git-secrets
        cd $GITHUB_WORKSPACE/git-secrets-checkout
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --install
      shell: bash
    - name: Register
      run: |
        # register git-secrets
        cd $GITHUB_WORKSPACE/git-secrets-checkout
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --register-aws
      shell: bash
    - name: Scan
      run: |
        # scan with git-secrets
        cd $GITHUB_WORKSPACE/git-secrets-checkout
        export PATH=PATH:${{ runner.temp }}/git-secrets-prefix/bin/
        ${{ runner.temp }}/git-secrets-prefix/bin/git-secrets --scan
      shell: bash
